name: 'test: Auto Project Assign'

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-milestone:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          milestone: 'roadmap'